version: '3.8'

services:
  api:
    build: 
      context: .
      target: api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  postgres-data:
