version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/calories_db # URL de connexion PostgreSQL
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: calories-tracker
      POSTGRES_PASSWORD: cdadevops2024
      POSTGRES_DB: calories_tracker_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Mappe le port PostgreSQL

volumes:
  postgres-data:
